- name: Copy Jetson setup script
  copy:
    src: jetson_lab_client_setup.sh
    dest: /home/{{ ansible_user }}/jetson_lab_client_setup.sh
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run Jetson setup script
  shell: bash /home/{{ ansible_user }}/jetson_lab_client_setup.sh
  args:
    executable: /bin/bash