#/etc/nebula/config.yml
pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/jetson00.crt
  key: /etc/nebula/jetson00.key

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.168.100.1"
    - "192.168.100.2"

static_host_map:
  "192.168.100.1": ["lkk688.duckdns.org:8883"]
  "192.168.100.2": ["edgeai.duckdns.org:4242"]

relay:
  relays:
    - 192.168.100.2
  am_relay: false
  use_relays: true

punchy:
  punch: true

listen:
  host: 0.0.0.0
  port: 0

tun:
  dev: nebula1

firewall:
  inbound:
    - port: any
      proto: any
      host: any
  outbound:
    - port: any
      proto: any
      host: any

