- name: Install Prometheus & Grafana
  apt:
    name:
      - prometheus
      - grafana
    update_cache: yes
    state: present

- name: Enable and start services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - prometheus
    - grafana-server

- name: Configure Prometheus scrape targets
  copy:
    dest: /etc/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 10s
      scrape_configs:
        - job_name: 'jetsons'
          static_configs:
            - targets: [
              {% for host in groups['jetsons'] %}
              '{{ host }}:9100'{% if not loop.last %}, {% endif %}
              {% endfor %}
              ]

- name: Restart Prometheus
  systemd:
    name: prometheus
    state: restarted